=== codehaus/sonar-plugins/trunk/jmeter/jmeter-report-server/src/main/xsd/jtl.xsd
<?xml version="1.0"?>
<xs:schema 
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://xmlbeans.testresults.server.report.jmeter.excentia.es"
	xmlns="http://xmlbeans.testresults.server.report.jmeter.excentia.es"
	elementFormDefault="qualified"
>

	<xs:element name="testResults">
  	<xs:complexType>
	  	<xs:choice minOccurs="0" maxOccurs="unbounded">
			<xs:element name="httpSample" type="HttpSample" />
			<xs:element name="sample" type="Sample"/>
	    </xs:choice>
		<xs:attribute name="version" type="xs:string" />
	</xs:complexType>
	</xs:element>
  
  
  <xs:complexType name="TextEl">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="class" type="xs:string" />
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  
  
  <xs:complexType name="AssertionResult">
    <xs:sequence>
      <xs:element name="name" type="xs:string" minOccurs="0" maxOccurs="1"/>
      <xs:element name="failure" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
      <xs:element name="error" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
      <xs:element name="failureMessage" type="xs:string" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  
  
  <xs:complexType name="AbstractSample">
    <xs:sequence>
      <xs:element name="assertionResult" type="AssertionResult" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  
    <xs:attribute name="t" type="xs:long" use="required" />
    <xs:attribute name="it" type="xs:long" />
    <xs:attribute name="lt" type="xs:long" />
    <xs:attribute name="ts" type="xs:long" />
    <xs:attribute name="s" type="xs:boolean" />
    <xs:attribute name="lb" type="xs:string" />
    <xs:attribute name="rc" type="xs:string" />
    <xs:attribute name="rm" type="xs:string" />
    <xs:attribute name="tn" type="xs:string" />
    <xs:attribute name="dt" type="xs:string" />
    <xs:attribute name="de" type="xs:string" />
    <xs:attribute name="by" type="xs:long" />
    <xs:attribute name="sc" type="xs:long" />
    <xs:attribute name="ec" type="xs:long" />
    <xs:attribute name="ng" type="xs:long" />
    <xs:attribute name="na" type="xs:long" />
    <xs:attribute name="hn" type="xs:string" />
  </xs:complexType>
  
  
	<xs:complexType name="HttpSample">
	<xs:complexContent>
	<xs:extension base="AbstractSample" >
		<xs:sequence>
			<xs:element name="httpSample" type="HttpSample" minOccurs="0" maxOccurs="unbounded"/>
      
      <xs:element name="responseHeader" type="TextEl" minOccurs="0" maxOccurs="1" />
      <xs:element name="requestHeader" type="TextEl" minOccurs="0" maxOccurs="1" />
      <xs:element name="responseData" type="TextEl" minOccurs="0" maxOccurs="1" />
      <xs:element name="responseFile" type="TextEl" minOccurs="0" maxOccurs="1" />
      <xs:element name="cookies" type="TextEl" minOccurs="0" maxOccurs="1" />
      <xs:element name="method" type="TextEl" minOccurs="0" maxOccurs="1" />
      <xs:element name="queryString" type="TextEl" minOccurs="0" maxOccurs="1" />
      <xs:element name="redirectLocation" type="TextEl" minOccurs="0" maxOccurs="1" />
      
      <!-- 
        XXX cfillol: 
        In some versions the tagName is "java.net.URL" and in others is "url".
        We'll have to take care of this when getting info from xmlbeans. 
      -->
      <xs:element name="java.net.URL" type="TextEl" minOccurs="0" maxOccurs="1" />
      <xs:element name="url" type="TextEl" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
	</xs:extension>
	</xs:complexContent>
	</xs:complexType>
	
  
	<xs:complexType name="Sample">
	<xs:complexContent>
	<xs:extension base="AbstractSample" >
    <xs:sequence>
  		<xs:choice minOccurs="0" maxOccurs="unbounded">
  			<xs:element name="httpSample" type="HttpSample" />
  			<xs:element name="sample" type="Sample"/>
  	  </xs:choice>
      
      <xs:element name="responseHeader" type="TextEl" minOccurs="0" maxOccurs="1" />
      <xs:element name="requestHeader" type="TextEl" minOccurs="0" maxOccurs="1" />
      <xs:element name="responseData" type="TextEl" minOccurs="0" maxOccurs="1" />
      <xs:element name="responseFile" type="TextEl" minOccurs="0" maxOccurs="1" />
      <xs:element name="samplerData" type="TextEl" minOccurs="0" maxOccurs="1" />
    </xs:sequence>
	</xs:extension>
	</xs:complexContent>
	</xs:complexType>
	
</xs:schema>

=== codehaus/sonar-plugins/jmeter/jmeter-report-server/src/main/xsd/test-trans-full-27.jtl.xml
<?xml version="1.0" encoding="UTF-8"?>
<testResults version="1.2"
xmlns="http://xmlbeans.testresults.server.report.jmeter.excentia.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://xmlbeans.testresults.server.report.jmeter.excentia.es jtl.xsd">
<httpSample t="10" it="0" lt="5" ts="1350570764225" s="true" lb="ssc" rc="200" rm="OK" tn="Email Setup  1-1" dt="text" de="UTF-8" by="4208" sc="1" ec="0" ng="1" na="1" hn="server1">
  <assertionResult>
    <name>Response Assertion</name>
    <failure>false</failure>
    <error>false</error>
  </assertionResult>
  <httpSample t="5" it="0" lt="5" ts="1350570764225" s="true" lb="http://server.xyz.com/ssc" rc="302" rm="Moved Temporarily" tn="" dt="text" de="UTF-8" by="531" sc="1" ec="0" ng="0" na="0" hn="server1">
    <responseHeader class="java.lang.String">HTTP/1.1 302 Moved Temporarily
Date: Thu, 18 Oct 2012 14:30:37 GMT
Server: Apache/2.2.3 (Red Hat)
Location: http://server.xyz.com/ssc/
X-Powered-By: Servlet/2.5 JSP/2.1
Connection: close
Transfer-Encoding: chunked
Content-Type: text/html; charset=UTF-8
</responseHeader>
    <requestHeader class="java.lang.String">Connection: keep-alive
X-Requested-With: XMLHttpRequest
User-Agent: Jakarta Commons-HttpClient/3.1
Host: server.xyz.com
</requestHeader>
    <responseData class="java.lang.String">&lt;html&gt;&lt;head&gt;&lt;title&gt;302 Moved Temporarily&lt;/title&gt;&lt;/head&gt;&#xd;
&lt;body bgcolor=&quot;#FFFFFF&quot;&gt;&#xd;
&lt;p&gt;This document you requested has moved temporarily.&lt;/p&gt;&#xd;
&lt;p&gt;It&apos;s now at &lt;a href=&quot;http://server.xyz.com/ssc/&quot;&gt;http://server.xyz.com/ssc/&lt;/a&gt;.&lt;/p&gt;&#xd;
&lt;/body&gt;&lt;/html&gt;&#xd;
</responseData>
    <responseFile class="java.lang.String"></responseFile>
    <cookies class="java.lang.String"></cookies>
    <method class="java.lang.String">GET</method>
    <queryString class="java.lang.String"></queryString>
    <redirectLocation class="java.lang.String">http://server.xyz.com/ssc/</redirectLocation>
    <java.net.URL>http://server.xyz.com/ssc</java.net.URL>
  </httpSample>
  <httpSample t="5" it="0" lt="4" ts="1350570764230" s="true" lb="http://server.xyz.com/ssc/" rc="200" rm="OK" tn="Email Setup  1-1" dt="text" de="UTF-8" by="3677" sc="1" ec="0" ng="0" na="0" hn="server1">
    <responseHeader class="java.lang.String">HTTP/1.1 200 OK
Date: Thu, 18 Oct 2012 14:30:37 GMT
Server: Apache/2.2.3 (Red Hat)
Content-Length: 3367
Set-Cookie: JSESSIONID=p1J4QQSNvGh9t9bHqGmK2wh2SdpGYfxYvc90QFT2hB3vN7rKJQJq!1363674634; path=/; HttpOnly
X-Powered-By: Servlet/2.5 JSP/2.1
Connection: close
Content-Type: text/html; charset=UTF-8
</responseHeader>
    <requestHeader class="java.lang.String">Connection: keep-alive
X-Requested-With: XMLHttpRequest
User-Agent: Jakarta Commons-HttpClient/3.1
Host: server.xyz.com
</requestHeader>
    <responseData class="java.lang.String">&#xd;
&#xd;
&#xd;
&lt;!DOCTYPE html&gt;&#xd;
&#xd;
&lt;html&gt;&#xd;
&lt;head&gt;&#xd;
&#xd;
&#xd;
	&lt;title&gt;GlobeCom - Self Support Console Lite&lt;/title&gt;&#xd;
&#xd;
	&lt;!-- jQuery --&gt;&#xd;
	&lt;link type=&quot;text/css&quot; href=&quot;jquery/themes/ABC/jquery-ui-1.8.18.ABC.css&quot; rel=&quot;stylesheet&quot; /&gt;&#xd;
	&lt;link type=&quot;text/css&quot; href=&quot;jquery/themes/ABC/jquery-ui.css&quot; rel=&quot;stylesheet&quot; /&gt;&#xd;
	&lt;script type=&quot;text/javascript&quot; src=&quot;jquery/jquery-1.7.1.min.js&quot;&gt;&lt;/script&gt;&#xd;
	&lt;script type=&quot;text/javascript&quot; src=&quot;jquery/jquery-ui-1.8.18.custom.min.js&quot;&gt;&lt;/script&gt;&#xd;
&#xd;
	&lt;!-- CSS --&gt;&#xd;
	&lt;link type=&quot;text/css&quot; href=&quot;css/sscPortal_styles.css&quot; rel=&quot;stylesheet&quot; /&gt;&#xd;
	&lt;!--[if IE]&gt;&#xd;
	&lt;link type=&quot;text/css&quot; href=&quot;css/sscPortal_ie.css&quot; rel=&quot;stylesheet&quot; /&gt;&#xd;
	&lt;![endif]--&gt;&#xd;
&#xd;
	&lt;script&gt;&#xd;
	$(function(){&#xd;
		// BROWSER DETECTION&#xd;
		// allow all browsers except IE6 and below&#xd;
		if( /MSIE (\d+\.\d+)/.test(navigator.userAgent) ){&#xd;
			var ieVer = RegExp.$1;&#xd;
			if( ieVer &gt;= 7 ){&#xd;
				// allow IE7 and up, do nothing&#xd;
			}&#xd;
			else if( ieVer &lt; 7 ){&#xd;
				if( window.location.href.indexOf(&quot;welcome.jsp&quot;) &gt;= 0 ){&#xd;
					$(&quot;#browserError&quot;).css(&quot;display&quot;,&quot;block&quot;);&#xd;
					$(&quot;#loginDiv&quot;).css(&quot;display&quot;,&quot;none&quot;);&#xd;
				}&#xd;
				else{&#xd;
					$(&quot;.centerWrapper&quot;).css(&quot;display&quot;,&quot;none&quot;);	// ensure nothing is shown&#xd;
					location.href = &quot;welcome.jsp&quot;;&#xd;
				}&#xd;
			}&#xd;
		}&#xd;
	});&#xd;
	&lt;/script&gt;&#xd;
&#xd;
	&#xd;
&#xd;
&lt;script language=&quot;javascript&quot;&gt;&#xd;
	/* Invoking authenticateLogin function during page load */&#xd;
	window.onload = authenticateLogin;&#xd;
&#xd;
	/**&#xd;
	*   AJAX function call to submit the username and password for authenticating the container&#xd;
	*/&#xd;
	function authenticateLogin(){&#xd;
		var xmlhttp;&#xd;
		var url = &quot;/ssc/j_security_check?j_username=subscriber&amp;j_password=subscriber1&quot;;&#xd;
		var queryString = document.location.search.substring(1);&#xd;
&#xd;
		// code for IE7+, Firefox, Chrome, Opera, Safari&#xd;
		if( window.XMLHttpRequest ){&#xd;
			xmlhttp = new XMLHttpRequest();&#xd;
		}&#xd;
		// code for IE6, IE5&#xd;
		else{&#xd;
			xmlhttp = new ActiveXObject(&quot;Microsoft.XMLHTTP&quot;);&#xd;
		}&#xd;
		xmlhttp.onreadystatechange = function(){&#xd;
			if( xmlhttp.readyState == 4 ){&#xd;
				document.getElementById(&quot;loginForm&quot;).action = &quot;/ssc/welcome.jsp?&quot; + queryString;&#xd;
				document.getElementById(&quot;loginForm&quot;).submit();&#xd;
			}&#xd;
		}&#xd;
		xmlhttp.open( &quot;GET&quot;, url, true );&#xd;
		xmlhttp.send();&#xd;
	}&#xd;
&lt;/script&gt;&#xd;
&#xd;
&lt;/head&gt;&#xd;
&#xd;
&lt;body&gt;&#xd;
&lt;div id=&quot;motive&quot;&gt;&#xd;
&#xd;
		&lt;div id=&quot;mainHeaderStripe&quot;&gt;&#xd;
		&lt;div id=&quot;mainHeader&quot; class=&quot;centerWrapper&quot;&gt;&#xd;
			&lt;div id=&quot;logo&quot;&gt;&lt;/div&gt;&#xd;
			&lt;div id=&quot;appTitle&quot;&gt;Self Support Console&lt;/div&gt;&#xd;
		&lt;/div&gt;&#xd;
	&lt;/div&gt;&#xd;
	&lt;div class=&quot;centerWrapper&quot;&gt;&#xd;
				&lt;div id=&quot;primNav&quot;&gt;&#xd;
			&lt;ul&gt;&#xd;
				&lt;li id=&quot;nav_services&quot;&gt;My Services&lt;/li&gt;&#xd;
				&lt;li id=&quot;nav_devices&quot;&gt;My Devices&lt;/li&gt;&#xd;
				&lt;li id=&quot;nav_social&quot;&gt;Social&lt;/li&gt;&#xd;
				&lt;li id=&quot;nav_marketplace&quot;&gt;Marketplace&lt;/li&gt;&#xd;
			&lt;/ul&gt;&#xd;
		&lt;/div&gt;&#xd;
		&lt;div id=&quot;colMask&quot; class=&quot;noLeftNav&quot;&gt;	&lt;!-- add class=&quot;noLeftNav&quot; if hiding the nav --&gt;&#xd;
			&lt;div id=&quot;mainContent&quot;&gt;&#xd;
			&lt;!-- CONTENT --&gt;&#xd;
&#xd;
				&lt;div id=&quot;progressDiv&quot;&gt;&lt;img src=&quot;images/progress_lg.gif&quot;&gt;&lt;br&gt;Please Wait&lt;/div&gt;&#xd;
				&lt;form name=&quot;loginForm&quot; id=&quot;loginForm&quot; method=&quot;post&quot;&gt;&lt;/form&gt;&#xd;
&#xd;
			&lt;!-- /CONTENT --&gt;&#xd;
			&lt;/div&gt;&lt;!-- /mainContent --&gt;&#xd;
		&lt;/div&gt;&lt;!-- /colMask --&gt;&#xd;
				&lt;div id=&quot;mainFooter&quot; class=&quot;clearBoth&quot;&gt;&lt;img id=&quot;motiveLogo&quot; src=&quot;images/logo_motive.png&quot; align=&quot;left&quot;&gt;&lt;img id=&quot;alcatelLucentLogo&quot; src=&quot;images/logo_alcatelLucent.png&quot; align=&quot;right&quot;&gt;Copyright &amp;copy; 2006-2012 Alcatel-Lucent. All Rights Reserved.&lt;/div&gt;&#xd;
	&lt;/div&gt;&lt;!-- centerWrapper --&gt;&#xd;
&#xd;
&lt;/div&gt;&lt;!-- /motive --&gt;&#xd;
&lt;/body&gt;&#xd;
&lt;/html&gt;&#xd;
</responseData>
    <responseFile class="java.lang.String"></responseFile>
    <cookies class="java.lang.String"></cookies>
    <method class="java.lang.String">GET</method>
    <queryString class="java.lang.String"></queryString>
    <java.net.URL>http://server.xyz.com/ssc/</java.net.URL>
  </httpSample>
  <responseHeader class="java.lang.String">HTTP/1.1 200 OK
Date: Thu, 18 Oct 2012 14:30:37 GMT
Server: Apache/2.2.3 (Red Hat)
Content-Length: 3367
Set-Cookie: JSESSIONID=p1J4QQSNvGh9t9bHqGmK2wh2SdpGYfxYvc90QFT2hB3vN7rKJQJq!1363674634; path=/; HttpOnly
X-Powered-By: Servlet/2.5 JSP/2.1
Connection: close
Content-Type: text/html; charset=UTF-8
</responseHeader>
  <requestHeader class="java.lang.String">Connection: keep-alive
X-Requested-With: XMLHttpRequest
User-Agent: Jakarta Commons-HttpClient/3.1
Host: server.xyz.com
</requestHeader>
  <responseData class="java.lang.String">&#xd;
&#xd;
&#xd;
&lt;!DOCTYPE html&gt;&#xd;
&#xd;
&lt;html&gt;&#xd;
&lt;head&gt;&#xd;
&#xd;
&#xd;
	&lt;title&gt;GlobeCom - Self Support Console Lite&lt;/title&gt;&#xd;
&#xd;
	&lt;!-- jQuery --&gt;&#xd;
	&lt;link type=&quot;text/css&quot; href=&quot;jquery/themes/ABC/jquery-ui-1.8.18.ABC.css&quot; rel=&quot;stylesheet&quot; /&gt;&#xd;
	&lt;link type=&quot;text/css&quot; href=&quot;jquery/themes/ABC/jquery-ui.css&quot; rel=&quot;stylesheet&quot; /&gt;&#xd;
	&lt;script type=&quot;text/javascript&quot; src=&quot;jquery/jquery-1.7.1.min.js&quot;&gt;&lt;/script&gt;&#xd;
	&lt;script type=&quot;text/javascript&quot; src=&quot;jquery/jquery-ui-1.8.18.custom.min.js&quot;&gt;&lt;/script&gt;&#xd;
&#xd;
	&lt;!-- CSS --&gt;&#xd;
	&lt;link type=&quot;text/css&quot; href=&quot;css/sscPortal_styles.css&quot; rel=&quot;stylesheet&quot; /&gt;&#xd;
	&lt;!--[if IE]&gt;&#xd;
	&lt;link type=&quot;text/css&quot; href=&quot;css/sscPortal_ie.css&quot; rel=&quot;stylesheet&quot; /&gt;&#xd;
	&lt;![endif]--&gt;&#xd;
&#xd;
	&lt;script&gt;&#xd;
	$(function(){&#xd;
		// BROWSER DETECTION&#xd;
